version: "3.9"

services:
  php-webpage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    ports:
      - "8080:80" # Map container's port 80 to host's port 8080
    volumes:
      - ./php:/var/www/html # Mount PHP files for live updates
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: my_database
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306" # Expose MySQL port
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql # Persist database data

volumes:
  db_data: # Named volume for persistent database storage
